In [4]:
#1 Dimmensional array
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#Number of elements
print(a.size)

3


In [6]:
#Matrix size
print(a.shape)

(3,)


In [7]:
type(a)

numpy.ndarray

In [8]:
#2d matrix
b=np.array([[1,2,3],[10,20,30]])
print(b)

[[ 1  2  3]
 [10 20 30]]


In [9]:
#Number of elements
print(b.size)

6


In [10]:
#Matrix Size
print(b.shape)

(2, 3)


In [11]:
# print 2nd row 2nd column
print(b[1,1])

20


In [12]:
#print 1st row 
print(b[0,:])

[1 2 3]


In [13]:
#print 2rd column
print(b[:,1])

[ 2 20]


In [14]:
#print sum of elements
print(b.sum())

66


In [15]:
#print sum of columns
print(b.sum(axis=0))

[11 22 33]


In [16]:
#print sum of rows
print(b.sum(axis=1))

[ 6 60]


In [17]:
#exponential of matrix
print(np.exp(b))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [2.20264658e+04 4.85165195e+08 1.06864746e+13]]


In [18]:
#Square root of matrix
print(np.sqrt(b))

[[1.         1.41421356 1.73205081]
 [3.16227766 4.47213595 5.47722558]]


In [19]:
# print Zero Matrix
#Zero matrix elements are float
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# print Zero Matrix
#Zero matrix elements as Int
d=np.zeros((3,4),dtype=np.int16)
print(d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
# print ones Matrix
#ones matrix elements as Int
print(np.ones((3,4),dtype=np.int16))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [22]:
#arange function
# arrange 10 to 19 by step 2
e=np.arange(10,20,2)
print(e)

[10 12 14 16 18]


In [23]:
# 2d matrix
f=np.arange(12).reshape(4,3)
print(f)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [24]:
#3d matrix
g=np.arange(30).reshape(5,3,2)
print(g)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]


In [25]:
#linspace
h=np.linspace(10,20,15)
print(h)

[10.         10.71428571 11.42857143 12.14285714 12.85714286 13.57142857
 14.28571429 15.         15.71428571 16.42857143 17.14285714 17.85714286
 18.57142857 19.28571429 20.        ]


In [26]:
#basicoperations
a=np.array([10,20,30,40,50,60,70])
b=np.arange(7)
print("aray a-b", a-b)
print("aray a+b", a+b)
print("aray a*b", a*b)
print("aray a**2",a**2)

aray a-b [10 19 28 37 46 55 64]
aray a+b [10 21 32 43 54 65 76]
aray a*b [  0  20  60 120 200 300 420]
aray a**2 [ 100  400  900 1600 2500 3600 4900]


In [27]:
# matrix product
a=np.array([10,20,30])
b=np.array([2,4,6])
print("aray a*b", a*b)# element wise product
print(a.dot(b))# matrix product
print(np.dot(a,b))# matrix product

aray a*b [ 20  80 180]
280
280


In [28]:
# print any random number  2 row 3 coloumn
a=np.random.random((2,3))
print(a)

[[0.2600027  0.52558288 0.55994044]
 [0.61163876 0.53137432 0.36322585]]


In [29]:
# shape manupulation
b=np.array([[1,2,3],[5,6,7],[9,10,11],[13,14,15]])
print(b)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [30]:
#change matrix shape
print(b.reshape(3,4))

[[ 1  2  3  5]
 [ 6  7  9 10]
 [11 13 14 15]]


In [31]:
print(b.resize(4,3))

None


In [58]:
## index start from 0
height=5.5
np_height_m=np.array(height)*0.0254
print(np_height_m)


0.1397


In [59]:
weight=53
np_weight_kg = np.array(weight) * 0.453592
print(np_weight_kg)

24.040376


In [60]:
bmi = np_weight_kg / np_height_m ** 2 # devide
print(bmi)

1231.82338265503


In [61]:
light=bmi<21 # logical array where bmi<21
print(light)

print(bmi[light])
#print pmi where bmi<21

False
[]


In [66]:
## Array addition & multiplication
np_baseball=8
conversion=12
print(np_baseball*conversion)
print(np_baseball+conversion)

96
20


In [83]:
## basic statistics
# a is vector
a=12,56,23,34,45,
#np.mean(a)
#np.median(a)
print(np.mean(a))

34.0


In [84]:
b=12,12,12
np.median(b)


12.0

In [85]:
np.corrcoef(a)

1.0

In [86]:
np.std(a)


15.556349186104045

In [87]:

np.sort(a)

array([12, 23, 34, 45, 56])

In [88]:
np.sum(a)

170

In [93]:
np.round(2.345) 


2.0

In [92]:
np.round(2.345,2) 

2.35

In [94]:
h=np.round(np.random.normal(1.75,0.2,5000),2)
w=np.round(np.random.normal(60.3,15,5000),2)# np.random.normal(mean,stdv,number of sample)
np_city=np.column_stack((h,w))

In [95]:
print(h)
print(w)
print(np_city)

[1.92 2.05 1.61 ... 1.7  1.4  1.69]
[73.67 64.   52.22 ... 48.52 45.49 52.27]
[[ 1.92 73.67]
 [ 2.05 64.  ]
 [ 1.61 52.22]
 ...
 [ 1.7  48.52]
 [ 1.4  45.49]
 [ 1.69 52.27]]
